include:
  - project: ihp/julia/julia-gitlab-ci-templates
    ref: v1.5.0
    file: /templates.gitlab-ci.yaml
  - project: ihp/julia/julia-gitlab-ci-templates
    ref: v1.5.0
    file: /jobs/analyze_package.gitlab-ci.yaml
  - project: ihp/julia/julia-gitlab-ci-templates
    ref: v1.5.0
    file: /jobs/analyze_tests.gitlab-ci.yaml
  - project: ihp/julia/julia-gitlab-ci-templates
    ref: v1.5.0
    file: /jobs/format.gitlab-ci.yaml

.build_essential: &build_essential
  before_script:
    - !reference [.gitlab.redirect_git_for_ci_server_host, before_script]
    - apt-get update
    - apt-get install -y --no-install-recommends build-essential

analyze_package:
  << : *build_essential
  variables:
    CI_JULIA_JET_TARGET_DEFINED_MODULES: "true"
    CI_JULIA_VERSION: "1-bullseye"

analyze_tests:
  << : *build_essential
  variables:
    CI_JULIA_JET_TARGET_DEFINED_MODULES: "true"
    CI_JULIA_VERSION: "1-bullseye"

test:
  << : *build_essential
  stage: test
  parallel:
    matrix:
      - CI_JULIA_VERSION: ["1.6-bullseye", "1-bullseye"]
  extends:
    - .julia.setup
    - .julia.test
