name = "FiftyOneImageAnnotations"
uuid = "a00f948b-584f-4068-8192-b9768bfe7837"
authors = ["IHP Systems R&D <research@ihp.dk>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
