name = "FiftyOneImageAnnotations"
uuid = "a00f948b-584f-4068-8192-b9768bfe7837"
authors = ["IHP Systems R&D <research@ihp.dk>"]
version = "0.1.2"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
ImageAnnotations = "76a96b56-f16f-11e8-3761-3967fdcf98d3"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
GeometryBasics = "0.4"
ImageAnnotations = "0.6"
PythonCall = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
