name = "FiftyOneImageAnnotations"
uuid = "a00f948b-584f-4068-8192-b9768bfe7837"
authors = ["IHP Systems R&D <research@ihp.dk>"]
version = "0.1.0"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
PythonCall = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
